### ISSUE TITLE
Errors when interpolating the media selector for a block

### ISSUE THREAD

**Issue by mstarkman** [styled-components/stylelint-processor-styled-components#115]
I'm not sure if this is related to #110, so that is why I'm putting it in as a new issue.

I have the following code:

```js
const StyledSection = styled.section`
  padding: ${baseSpacing};

  ${forMobileOnly} {
    padding: ${smallSpacing};
  }
`
```
The `forMobileOnly` variable is set to `@media (max-width: 640px)`.  I'm getting to following stylelint errors:

```
 15:3   ✖  Unexpected empty line before declaration                       declaration-empty-line-before            
 15:30  ✖  Expected newline after ";" in a multi-line declaration block   declaration-block-semicolon-newline-after
 15:31  ✖  Expected empty line before rule                                rule-empty-line-before
```

For now, I'm working around by adding the following disable statements.  

```js
const StyledSection = styled.section`
  padding: ${baseSpacing};

  ${forMobileOnly} { /* stylelint-disable-line */
    /* stylelint-disable-next-line declaration-empty-line-before */
    padding: ${smallSpacing};
  }
`
```

Do you know of another way of attempting to do what I am doing without putting in the disable statements or is this directly related to #110?

**Comment by mxstbr** [comment]
This isn't released yet but [interpolation tagging](https://www.styled-components.com/docs/tooling#interpolation-tagging) is the solution for your issue!

```JS
const StyledSection = styled.section`
  padding: ${baseSpacing};

  ${/* sc-selector */ forMobileOnly} {
    padding: ${smallSpacing};
  }
`
```

We're going to release that sometime this or next week, so stay tuned!

**Comment by mstarkman** [comment]
@mxstbr Thanks!  Will that be an update to this repo or to styled-components itself?

**Comment by mxstbr** [comment]
This repo, going to push a 1.0 release of the stylelint processor very soon!

**Comment by kusmierz** [comment]
@mxstbr any ETA? :)
