### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by Pajn** [styled-components/stylelint-processor-styled-components#12]
I don't know how feasible it is but thought that I should put it out here.
It would be awesome with Typescript support.

**Comment by schickling** [comment]
Not sure if this is related to Typescript (which we're using) but I'm getting the following error:

![image](https://cloud.githubusercontent.com/assets/1567498/21269809/806e56f0-c3b4-11e6-9948-dd78e9e2c21d.png)

**Comment by ErikCupal** [comment]
Hopefully in future https://github.com/babel/babylon/issues/320

**Comment by ismay** [comment]
Is that something that should be solved in this processor though? It would be more straightforward if we could keep this processor agnostic of any static typing the user might be using.

**Comment by gcazaciuc** [comment]
Did a PR to address this issue. I've taken the same approach as Prettier JS relying on typescript-eslint-parser to convert the Typescript AST to Estree AST.

**Comment by mxstbr** [comment]
What a great PR, thank you so much @gcazaciuc! 😍 

Released in v0.1.1 👌

**Comment by valorize** [comment]
I think it is really cool to have typescript support. But I do not use typescript and get an error as follows: 
`npm WARN typescript-eslint-parser@7.0.0 requires a peer of typescript@* but none was installed.`
Do you know how to suppress this warning?

**Comment by emilgoldsmith** [comment]
Yep update :), it was removed as a peerDependency

**Comment by emilgoldsmith** [comment]
Or actually nevermind, sorry, that specific warning we probably can't do anything about, it is just a warning though. We need to include the parser as a dependency for if you use it for Typescript, though the code will never run unless you actually run it on a Typescript file and therefore you won't actually need Typescript installed. But I guess that warning is from the `typescript-eslint-parser` package, so not much we can do about that as it needs to come bundled with the processor.

**Comment by valorize** [comment]
Ok, thanks for your clarification anyway.
