### ISSUE TITLE
Interpolation tagging doesn't work with Typescript file

### ISSUE THREAD

**Issue by huy-nguyen** [styled-components/stylelint-processor-styled-components#130]
I tried to lint this this typescript file (simplified):
```typescript
import styled from 'styled-components';

const StyledTable = styled(StyledTableBase)`
  ${tableColumnSelector}:nth-child(1) {
    width: ${rankColumnWidth};
    text-align: left;
    padding-left: 4px;
  }
`;
```
and got this error:
```

 4:30  ✖  Expected newline after ";" in a multi-line declaration block   declaration-block-semicolon-newline-after
 4:30  ✖  Expected empty line before rule                                rule-empty-line-before
```
I then tried to use the interpolation tagging with `sc-selector`:
```typescript
import styled from 'styled-components';

const StyledTable = styled(StyledTableBase)`
  ${/* sc-selector */tableColumnSelector}:nth-child(1) {
    width: ${rankColumnWidth};
    text-align: left;
    padding-left: 4px;
  }
`;
```
but got the same errors. I then tried using `sc-custom` as the last resort:
```typescript
import styled from 'styled-components';

const StyledTable = styled(StyledTableBase)`

  ${/* sc-custom 'th' */tableColumnSelector}:nth-child(1) {
    width: ${rankColumnWidth};
    text-align: left;
    padding-left: 4px;
  }
`;
```
but still got the same errors. Here's my `stylelint` config:
```js
module.exports = {
  processors: ['stylelint-processor-styled-components'],
  extends: [
    'stylelint-config-standard',
    'stylelint-config-styled-components',
  ],
  syntax: 'scss',
}
```
Is this a bug with the processor or am I not using it correctly? Here are the relevant package versions.

- `stylelint` 8.1.1
- `stylelint-config-standard` 17.0.0
- `stylelint-processor-styled-components` 1.0.0
- `stylelint-config-styled-components` 
- `typescript` 2.5.2 (but I'm not using any 2.5 feature and the example still fails with `typescript-eslint-parser` 8.0 which supports `typescript` 2.5)

**Comment by mxstbr** [comment]
Can you try tagging your `${rankColumnWidth}` interpolation? We're having some issues with line numbers at the moment (ref #128) so it might be that's breaking it?

**Comment by emilgoldsmith** [comment]
Hmm, my best guess at the moment is that the processor inserts an extra semicolon after `rankColumnWidth` but I don't think it should...

Yeah it'd be helpful @huy-nguyen if you could do a bit of "binary search" to find exactly what causes it as the errors make it sound like it's not the selectors that are a problem, and find the minimum change to your css that'll make it stop erroring as that'll give us a better idea.

**Comment by huy-nguyen** [comment]
@mxstbr I tried this
```typescript
import styled from 'styled-components';

const StyledTable = styled.div`
  ${/* sc-selector */tableColumnSelector}:nth-child(1) {
    width: ${/* sc-value */ rankColumnWidth};
  }
`;
``` 
and this (removed semicolon):
```typescript
import styled from 'styled-components';

const StyledTable = styled.div`
  ${/* sc-selector */tableColumnSelector}:nth-child(1) {
    width: ${/* sc-value */ rankColumnWidth}
  }
`;
```
and this
```typescript
import styled from 'styled-components';

const StyledTable = styled.div`
  ${/* sc-selector */tableColumnSelector}:nth-child(1) {
    width: ${/* sc-custom '5px' */ rankColumnWidth};
  }
`;
```
but all gave the same errors. I'm not sure what else to try.

**Comment by emilgoldsmith** [comment]
Well this all helps of course, as it narrows it down to the interpolations though that was probably already pretty clear.

What about trying replacing each of the interpolations by a normal constant css string and seeing which one is causing the error like that? :)

**Comment by emilgoldsmith** [comment]
Great, that's very helpful. 

If you want to be even more helpful you can submit a PR with a breaking test like what was just done in #129 for #128. Then we'll get on it.

Given your extra tests I also think I'll change the tag to bug as it seems pretty obvious from those tests that the fault is somewhere on our end.

**Comment by huy-nguyen** [comment]
@emilgoldsmith I'm in a bit of a crunch right now to clone, add the tests and make a PR but I think it wouldn't take much time for someone else to pick it up from here.

**Comment by emilgoldsmith** [comment]
Yeah no worries, no requirements, just suggestions for positive ways to help speed up the process :).

**Comment by chinesedfan** [comment]
The current processor implementation can't recognize the selector interpolation here. And it will be substituted by `-styled-mixin${count}: dummyValue;`, which causes the first warning. Maybe #110 should also take this issue into considerations.

Even with interpolation tagging, it doesn't work because `typescript-eslint-parser` has moved support of attaches comments to ESLint from [v0.1.0](https://github.com/eslint/typescript-eslint-parser/pull/49). There are no leadingComments or trailingComments in parsed nodes. As #143 recommended, once babylon@7 was released, interpolation tagging will work.

**Comment by emilgoldsmith** [comment]
> typescript-eslint-parser has moved support of attaches comments to ESLint from v0.1.0. There are no leadingComments or trailingComments in parsed nodes.

Oh that makes sense, thanks for that information @chinesedfan, because then of course we can't do the interpolation tagging. We should probably also add this to the README on the website, I'll get on that later today.

**Comment by chinesedfan** [comment]
> We should probably also add this to the README on the website, I'll get on that later today.

Hi @emilgoldsmith, have it been added? Not a push, just curious. 😄

**Comment by emilgoldsmith** [comment]
Nope I must've forgotten! Thanks for the reminder I'll do it right now

**Comment by wachunga** [comment]
Any suggestions on workarounds for this? Currently I'm resorting to `/* stylelint-disable */`.

**Comment by emilgoldsmith** [comment]
Hmm, that's probably the best approach as of right now I'm sorry!

**Comment by emilgoldsmith** [comment]
#143 should have fixed this, publishing now

**Comment by huy-nguyen** [comment]
Thanks for fixing it!
