### ISSUE TITLE
Catch Babel parsing errors

### ISSUE THREAD

**Issue by adrianmcli** [styled-components/stylelint-processor-styled-components#131]
When I'm editing `.js` files with the [Stylelint plugin](https://github.com/shinnn/vscode-stylelint) in VSCode, I get spammed with popup error messages from babylon.

For example:

```
SyntaxError: Unexpected token, expected ;(50:12) at Parser.pp$5.raise (/home/hugo/projects/liber/liber-app/node_modules/babylon/lib/index.js:4454:13) at Parser.pp.unexpected (/home/hugo/projects/liber/liber-app/node_modules/babylon/lib/index.js:1761:8) at Parser.pp.semicolon (/home/hugo/projects/liber/liber-app/node_modules/babylon/lib/index.js:1742:38) at Parser.pp$1.parseVarStatement (/home/hugo/projects/liber/liber-app/node_modules/babylon/lib/index.js:2170:8) at Parser.p
```

My `.stylelintrc`:

```
{
  "processors": ["stylelint-processor-styled-components"],
  "extends": [
    "stylelint-config-standard",
    "stylelint-config-styled-components"
  ],
  "syntax": "scss"
}
```

Another user had the same problem here: https://github.com/shinnn/vscode-stylelint/issues/89

[According to the author of the plugin](https://github.com/shinnn/vscode-stylelint/issues/89#issuecomment-317180865), it seems that it's a bug with the processor (hence why I made this issue in this repo). He says it's because this processor does not adhere to the original stylelint behaviour to syntax errors as described [here](https://github.com/stylelint/stylelint/blob/8.0.0/docs/user-guide/node-api.md#syntax-errors):

> stylelint.lint() does not reject the Promise when your CSS contains syntax errors.

I'm completley new to Stylelint and I don't really know how it works, so this is where my research stopped. If anyone has some insight, that would be extremely helpful.

**Comment by orta** [comment]
Yep, and a fail generally works fine for us:

<img width="1366" alt="screen shot 2017-09-24 at 6 34 26 am" src="https://user-images.githubusercontent.com/49038/30781731-6cea8308-a0f2-11e7-9080-c61af85d58b6.png">

The offsets are usually wrong, but we have a complicated babel setup running typescript first, so we just deal with it

**Comment by mxstbr** [comment]
Hmm interesting, so it's gotta be something in your local setup @adrianmcli. I don't know what this means or what we should have to change:

> stylelint.lint() does not reject the Promise when your CSS contains syntax errors.

*Note: I think the wrong offsets are due to #128 (see failing test in #129), any help getting that fixed appreciated too!*

**Comment by orta** [comment]
Form the sounds of it, the issue is that an exception is being raised in the babel parser that _isn't_ being caught and returned as an object with the right formatting to say there is an issue. I don't think they ever expect you to be throwing an error, which seems like a reasonable assumption.

**Comment by adrianmcli** [comment]
@orta 

So are you not getting the popups that I am getting? And you are using the same vscode [plugin](https://github.com/shinnn/vscode-stylelint/) with comparable configuration?

Also, would you have any idea as to why the author of the plugin thinks it's a bug with the processor? I'm just trying to find a solution here.

**Comment by orta** [comment]
Nope, never seen popups like that - and yeah, I added the support for that extension: https://github.com/shinnn/vscode-stylelint/pull/82

I think it's this: an exception is being raised in a babel parser in this lib that isn't being caught and then returned as an object with the right formatting to say there is an issue. I don't think they ever expect you to be throwing an error, which seems like a reasonable assumption

**Comment by emilgoldsmith** [comment]
Okay @orta so you reckon this issue should for example be renamed to "Errors not being caught correctly" and we should add a `.catch` statement somehwere or something of the likes?

**Comment by orta** [comment]
Yep 👍

**Comment by Undistraction** [comment]
For what it's worth I have the same issue. The moment I start editing a JS file I get a deluge of alerts. It makes this plugin unusable unfortunately as my only option is to remove Javascript from stylelint's list of types.
