### ISSUE TITLE
When using --fix it remove all lines of files without styled-components

### ISSUE THREAD

**Issue by gartz** [styled-components/stylelint-processor-styled-components#133]
I did the basic configuration recommended in the docs, when I run:

```
stylelint 'src/**/*.js' --fix
```

Instead of ignoring files without `styled-components` it replaces the files by an empty file.

Config file:
```
{
  "processors": ["stylelint-processor-styled-components"],
  "extends": [
    "stylelint-config-standard",
    "./src/.stylelintrc",
    "stylelint-config-styled-components"
  ]
}
```

Packages version:
```
    "stylelint": "^8.2.0",
    "stylelint-config-standard": "^17.0.0",
    "stylelint-config-styled-components": "^0.1.1",
    "stylelint-processor-styled-components": "^1.0.0",
```

**Comment by emilgoldsmith** [comment]
This isn't a bug I'm afraid, we just simply can't support `--fix`. It's all in the way stylelint processors are written, Stylelint simply calls our processor to extract the css from a given file, and I guess they then assume that that constitutes the whole file, so when you use `--fix` and we say "there's no CSS in this file" it'll return an empty file.

I'm also assuming that in any other files it is removing all the js and just outputting the CSS right?

If you want to take this up anywhere it should be in the Stylelint repo, but to be honest I also see it as a very challenging task for them. How would you autofix interpolations? What API would enable that?

We should maybe add a note in the docs about this though (I mean, `--fix` not being supported), but for now I'll close this issue as there's nothing we can do about it, and probably nothing will be done about it.

**Comment by emilgoldsmith** [comment]
https://github.com/stylelint/stylelint/issues/2617 and https://github.com/stylelint/stylelint/issues/2592 for reference

**Comment by gartz** [comment]
I think the solution of add a mention in the documentation will help a lot.

I agree that this isn’t an easy task. I would love to implement such, but I have no free time to do it. :/

About the interpolation, it needs to recursively check for strings inside interpreted blocks and ignore if it’s not at least a property:value css format. Not easy, not impossible, won’t be perfect.

Thanks for the clarification.

**Comment by emilgoldsmith** [comment]
Well for whatever fix, it still has to be Stylelint that implements it, not us, and I don't quite think you understand what I mean when you write 

>About the interpolation, it needs to recursively check for strings inside interpreted blocks and ignore if it’s not at least a property:value css format. Not easy, not impossible, won’t be perfect.

as the thing is we would still need to somehow tell Stylelint (and they would have to implement an API for it) what the actual CSS is, and then where to change what in order to fix things which would be incredibly complicated as we change the indentation, replace interpolations by placeholder and all kinds of things.

Your solution also seems to assume that everything is written inline, but if it's not you need to start evaluating all the Javascript which could become very expensive for a linter and really slow it down, and that is also why we chose not to go down that path and use interpolation tagging in our v1.0 release instead.

Adding something to the docs though for sure. If you want feel free to submit a PR to the styled-components website @gartz otherwise I might do it later today as it should just be a quick note.

**Comment by gartz** [comment]
It’s late here, I’m only answering emails by now.

I definitely agree that resolve interpolation will be very limited. You can’t call functions or evaluate their returns. As I said the only case is when find a string with a CSS key:value, even that is hard, would need an AST like Babel to get a few possible cases, what is heavy and too complex.

I would ignore such and only fix what is easy to test like plain CSS in the template string. Ignore variables and functions in it.

Please if you can do tonight the PR with a doc warning that the —fix doesn’t work, that will be the best, I can only do tomorrow.

Thanks.

**Comment by emilgoldsmith** [comment]
I'll do the docs PR now :).

But yeah regarding this: 
> I would ignore such and only fix what is easy to test like plain CSS in the template string. Ignore variables and functions in it.

I'm not sure if you're implying this is something we could implement or just continuing the discussion for discussion's sake, but just to once again clarify if it's the former: Stylelint doesn't support this for processors, so it's all hypothetical, this processor is only an addon for Stylelint and so it is limited what Stylelint allows us to do. So at this moment there is literally nothing we can do, all the rest of the discussion from my side was just a hypothetical of how it would probably still be very hard even if Stylelint implemented a new API that somehow addressed the usage of `--fix`

**Comment by emilgoldsmith** [comment]
https://github.com/styled-components/styled-components-website/pull/135

**Comment by gartz** [comment]
It need Stylelint to implement a way to custom output the string for the file, to be possible as you said before.

Can’t be done with a processor without that implementation.

If they add that possibility, that’s how I would add to the feature.

I was sharing hypothetical thoughts on how to do that, most probably would need another project using Babel AST to extract the css from the code, then apply the changes.

Thanks for everything. You did a great work with this preprocessor project! Hope I can contribute somehow in the future.

**Comment by gucong3000** [comment]
https://github.com/stylelint/stylelint/issues/3264
