### ISSUE TITLE
[stylelint-config-styled-components] Loads files without styled-components

### ISSUE THREAD

**Issue by vladimirvolek** [styled-components/stylelint-processor-styled-components#135]
According [this](https://www.styled-components.com/docs/tooling#setup) docs, files without styled-components should be ignored.

![image](https://user-images.githubusercontent.com/3112191/31728699-49e63714-b42d-11e7-8b9c-c01be1e9f325.png)
It's linting files with content:
```
export default {
    test: 'test'
};
```

**Comment by vladimirvolek** [comment]
ehh missing
```
"processors": ["stylelint-processor-styled-components"]
```

**Comment by emilgoldsmith** [comment]
Hmm why do you keep closing this issue? You want us to respond yes?

So you're saying that our processor lints a JS file that contains nothing but
```js
export default {
    test: 'test'
};
```

??

What is the exact Stylelint output that you get?
