### ISSUE TITLE
Atom support

### ISSUE THREAD

**Issue by ZwaarContrast** [styled-components/stylelint-processor-styled-components#15]
Quick question:

Is it possible to enable this package when using the linter-stylelint plugin for atom?

Installing this package allows me to run a command from the terminal, and it properly picks up styling in .js files, but it does not work with [https://atom.io/packages/linter-stylelint](Atom linter-stylelint plugin). Any ideas how to get this working?

If it's easy, it might be nice to include in the documentation.

**Comment by mxstbr** [comment]
Not yet, see https://github.com/AtomLinter/linter-stylelint/issues/235

**Comment by mxstbr** [comment]
Would be awesome if somebody could hack on that!
