### ISSUE TITLE
Source maps don't get assigned during CssSyntaxError

### ISSUE THREAD

**Issue by emilgoldsmith** [styled-components/stylelint-processor-styled-components#154]
It seems from #153 that the source maps don't run, and actually not even the `result()` function in `index.js` is run when there's a CssSyntaxError, I'm not quite sure if this is something we can actually do something about as it seems that Stylelint simply doesn't "give back control" to us in the case of a CssSyntaxError, but it should definitely be looked into as it's of course confusing behavior for users.

**Comment by chinesedfan** [comment]
I met this problem and opened an issue as [stylelint#3050](https://github.com/stylelint/stylelint/issues/3050). When CssSyntaxError occurred, our processor can do nothing until `stylelint` solves that.

**Comment by emilgoldsmith** [comment]
Yeah I see, very nicely documented issue with all the links to source, if we have some time we could maybe make the contribution to `stylelint` ourselves.

Also, thanks for the clarification here :)

**Comment by emilgoldsmith** [comment]
I'm working on a PR at the moment by the way, so no need for anyone else to start.

**Comment by emilgoldsmith** [comment]
PR submitted: https://github.com/stylelint/stylelint/pull/3063

when this gets merged in this should be automatically fixed, but we should also add a few regression tests, and probably a note in the README or the docs on the website that you need that specific version of `stylelint` in order for the source maps to work. At that point we can also add the fact the `--fix` doesn't work, if we haven't already done that.

**Comment by emilgoldsmith** [comment]
#167 This should now work as long as you upgrade your stylelint version to v9+
