### ISSUE TITLE
Stylelint not working with `withConfig`

### ISSUE THREAD

**Issue by inferusvv** [styled-components/stylelint-processor-styled-components#159]
My styled components are declared in next way:

```
export const IconWrapStyled = styled.div.withConfig({
  displayName: 'IconWrapStyled',
})`
  height: 2.083vw;
  width: 2.083vw;
  svg {
    height: 100%;
  width: 100%;
  }
`;
```

When I remove `withConfig` - linter works. Otherwise it don't.

**Comment by mxstbr** [comment]
You should never ever use `.withConfig` manually, which is why none of our tooling supports it. Let the Babel plugin automatically add it.
