### ISSUE TITLE
using sc-tag conflicts with standardjs

### ISSUE THREAD

**Issue by aehrt55** [styled-components/stylelint-processor-styled-components#179]
[Repository to reproduce](https://github.com/aehrt55/standardjs-stylelint-styled-components-conflict-example)

I use both [standardjs](https://github.com/standard/standard) and stylelint-processor-styled-components to lint my component. When I add [sc-tag](https://www.styled-components.com/docs/tooling#interpolation-tagging) to avoid **CssSyntaxError**, **Standardjs** throw an error `Unexpected space(s) after '${'`. Could I use these lint tools together? or any suggestion to lint both js & css for styled-components?

**Comment by emilgoldsmith** [comment]
Thanks for the repo to reproduce @aehrt55, that helps so much!

So let me be clear, it's only when you run the standardjs command that you get errors right? Not when you run `stylelint`?

**Comment by aehrt55** [comment]
@emilgoldsmith Yes, I get error when I run `standardjs`. But if I remove **sc-tag** from code, I will get error from `stylelint` and `standardjs` will lint correctly.

**Comment by emilgoldsmith** [comment]
I think my best suggestion for you right now is to switch to `prettier` maybe, that seems to do the same job (I never used StandardJs before but from their webpage it sounds like it's a tool with a similar goal to Prettier). I just downloaded your repo and tried running prettier on it with standard options and it didn't cause any errors. Also, Prettier has put in significant effort to make it work well with Styled Components actually, which is really nice! See [this issue](https://github.com/prettier/prettier/issues/2350) for example (lots of nice crossed out issues!)

**Comment by aehrt55** [comment]
Thanks for your suggestion. I will try it.

**Comment by aehrt55** [comment]
I think `standardjs` is like a preset for `eslint`, it seems that `prettier` cannot replace what `standardjs` do.

**Comment by emilgoldsmith** [comment]
Does this solve that issue? https://prettier.io/docs/en/eslint.html

**Comment by emilgoldsmith** [comment]
Anyway, I'm closing this issue as there's of course nothing we can do about it directly, I'm afraid you'd probably have to ask standardjs to change the style they enforce :(. But feel free to ask any more questions and I hope that you figure out a good developer environment setup with our processor!
