### ISSUE TITLE
Not working properly with stylelint 9.2.0

### ISSUE THREAD

**Issue by yoannmoinet** [styled-components/stylelint-processor-styled-components#180]
Hi, I've had issue making this work with the latest stylelint 9.2.0.

Everything is working fine with a very basic config file and stylelint 9.1.3 (previous version)

```
{
  "processors": ["stylelint-processor-styled-components"],
  "extends": [
    "stylelint-config-standard",
    "stylelint-config-styled-components"
  ]
}

```

It's outputting the errors correctly.
But when using with stylelint 9.2.0, nothing gets outputted.

I've tried removing the processor and having a basic css file, everything's working as intended.

Something from [this release](https://github.com/stylelint/stylelint/releases/tag/9.2.0) might have broke the processor, but no errors get thrown.

**Comment by emilgoldsmith** [comment]
Since there aren't any hints in the changelog about something changing for processors it seems it may be unintentional breakage on the Stylelint side, could you please try submitting an issue there first and seeing what you get back? They may have broken the processor API

**Comment by yoannmoinet** [comment]
Here you go @emilgoldsmith. 
stylelint/stylelint#3252

**Comment by emilgoldsmith** [comment]
Thanks! Let's see what they say

**Comment by chinesedfan** [comment]
@stramel Can you open a new issue with some details? Then we can track more effectively. Thanks.
