### ISSUE TITLE
Conflict between Stylelint and Atom Beautify

### ISSUE THREAD

**Issue by Jariway** [styled-components/stylelint-processor-styled-components#188]
When formatting the text with Atom these errrors appear. The problem is solved after removing the spaces, but It's quite anonying. ¿Any solution?
![captura](https://user-images.githubusercontent.com/17798459/40364552-ee6fe376-5dd2-11e8-80e6-dedd33c34de0.PNG)

**Comment by chinesedfan** [comment]
This is the project of `styled-components/stylelint-processor-styled-components`, but not `stylelint`. I think error descriptions are very clear: expected indentation of 2 spaces and end-of-source newline.

To solve your problem, you can go to [stylelint/stylelint](https://github.com/stylelint/stylelint) to find ways to config stylelint compatible with `beautify`.
