### ISSUE TITLE
Interoperate with SublimeLinter?

### ISSUE THREAD

**Issue by emusgrave** [styled-components/stylelint-processor-styled-components#19]
Does anyone know how to get this to operate with SublimeLinter-contrib-styelint? My guess is that it doesn't work out of the box because that package is only scanning CSS files, not JS/JSX.

**Comment by funwithtriangles** [comment]
I'm having trouble also. Using SublimeLinter and [SublimeLinter-contrib-stylelint].(https://github.com/kungfusheep/SublimeLinter-contrib-stylelint)

Linting works fine as a script from `package.json` but nothing is happening with SublimeLinter. SublimeLinter doesn't throw any warnings but isn't doing anything. I think @emusgrave might be on to something with JS/CSS issue...

**Comment by mxstbr** [comment]
Yep, this doesn't work right now :cry: I don't think there's anything from our side we can do here, please let the SublimeLinter people know!
