### ISSUE TITLE
get duplicate selector error, but there is no duplicate selector

### ISSUE THREAD

**Issue by kuzkokov** [styled-components/stylelint-processor-styled-components#193]
Hello guys. So I have this peace of code:

```
const Wrapper = styled(Box)`
  line-height: 0;
  // line 36
  :hover {
    ${FirstInsideComponent} { // line 38
      visibility: visible;
    }
  
    ${SecondInsideComponent} { // line 42
      opacity: 1;
    }
  }
`;
```
And I get a next issues:

>  38:33  ✖  Unexpected duplicate selector ".selector4 :hover ", first used at line 36   no-duplicate-selectors
> 42:33  ✖  Unexpected duplicate selector ".selector4 :hover ", first used at line 36   no-duplicate-selectors

If run stylelint with --fix flag I get this:
```
.selector4 {
  line-height: 0;
  
  :hover {
    -styled-mixin0: dummyValue; {
      visibility: visible;
    }
  
    -styled-mixin1: dummyValue; {
      opacity: 1;
    }
  }
}
```

I'm not sure, but I think this processor is causes the issue. Or am I doing something wrong?

**Comment by chinesedfan** [comment]
@kuzkokov The processor can not always parse interpolations with right things. But you can use [interpolation-tagging](https://www.styled-components.com/docs/tooling#interpolation-tagging) to help it.

```
const Wrapper = styled(Box)`
  line-height: 0;
  // line 36
  :hover {
    ${/* sc-custom 'div' */ FirstInsideComponent} { // line 38
      visibility: visible;
    }
  
    ${/* sc-custom 'p' */ SecondInsideComponent} { // line 42
      opacity: 1;
    }
  }
`;
```

**Comment by kuzkokov** [comment]
Thanks for pointing, it's worked.
