### ISSUE TITLE
comment-empty-line-before when using example media template function

### ISSUE THREAD

**Issue by joggienl** [styled-components/stylelint-processor-styled-components#194]
I am experiencing a stylelint error: `Expected empty line before comment comment-empty-line-before` when using the media template function to write media queries. The code corresponding to this is on the styled-components homepage: https://www.styled-components.com/docs/advanced#media-templates

```js
const sizes = {
  desktop: 992,
  tablet: 768,
  phone: 376
}

// Iterate through the sizes and create a media template
const media = Object.keys(sizes).reduce((acc, label) => {
  acc[label] = (...args) => css`
    @media (max-width: ${sizes[label] / 16}em) {
      ${css(...args)}
    }
  `

  return acc
}, {})
```

If I would now create a component as following, stylelint will give me a couple of errors.

```js
const Content = styled.div`
  height: 1em;
  width: 1em;
  background: papayawhip;

  /* Now we have our methods on media and can use them instead of raw queries */
  ${media.desktop`
    height: 4em;
    width: 3em;
    background: dodgerblue;
  `}
`;
```

It seems that the only way around this and preserving the way to write the media query is to add the `/* stylelint-disable comment-empty-line-before */` comment before adding the query.

Of course I could write three single `${media.desktop}` statements, but that doesn't seem the right way to do this.

```js
const Content = styled.div`
  height: 1em;
  width: 1em;
  background: papayawhip;

  /* below does not seem to be the right approach imo */
  /* it will generate a media query for each line, that seems overkill */
  ${media.desktop`height: 4em;`}
  ${media.desktop`width: 3em;`}
  ${media.desktop`background: dodgerblue;`}
`;
```

Is this a bug or do I simply need to change the way i am doing (using) this? Any help is appreciated!

Setup: regular react-boilerplate project with styled-components enabled and also the stylelint setup just as described on the styled-components website.

**Comment by Undistraction** [comment]
I'm seeing this too when using interpolations:

```
  align-items: center;
  width: 100%;
 
  ${example(2)};

  ${Header} {
  }
```

This is flagged at the point of each interpolation as:

> [stylelint] Unexpected empty line before declaration (declaration-empty-line-before)

Other than commenting every time I use an interpolation (as per @joggienl's examples above), the only way to prevent the errors is to remove all whitespace, making things a lot less readable. 

Is there any way you can allow whitespace before interpolations?

**Comment by joggienl** [comment]
To be extra clear from my side, the comments in the examples I used are not giving these errors. As soon as I do an interpolation to the `media` function, it does.

**Comment by Undistraction** [comment]
@joggienl Are you using `stylelint-config-recommended`? in your `.stylintrc`?

**Comment by joggienl** [comment]
@Undistraction, I am using the standard as provided per react-boilerplate. Which is configured in the package.json by the way, not in a separate `.stylelintrc` file.

I am not sure what you mean with "old recommendation". The `stylelint-config-standard` extends `stylelint-config-recommended`, so it is not an "older" version, it just turns on more additional rules for stylelint.

See https://github.com/stylelint/stylelint-config-standard for more on that.

**Comment by Undistraction** [comment]
I mean old as in that was what _was_ recommended by this lib.

**Comment by joggienl** [comment]
Thanks for the extra explanation @Undistraction!

I checked, with the `styled-config-recommended` I do not get the error as described. But since there are a lot of rules not defined that would also make sense.

I think this error should still not appear when working with the `styled-config-standard` package. For me it provides a lot of sane defaults I like to use to write my styled-components with. I looked at why standard changed to recommended, that was due to better supporting a workflow with Prettier (which I do not use at this moment) due to conflicting (stylistic)rules.

At this point I think that changing to the `styled-config-recommended` configuration is not the real solution to this problem.

**Comment by Undistraction** [comment]
@joggienl That makes sense. I'm using prettier so I'm alright with this decision. I really recommend switching to prettier. It's one of the biggest development time-savers you can find. It's certainly tough to accept some of its decisions, but after not so long you will be glad you switched.

**Comment by joggienl** [comment]
most probably some day I will, but that is not related (and feasible) right now ;-)
