### ISSUE TITLE
Wrong lint result

### ISSUE THREAD

**Issue by ZxBing0066** [styled-components/stylelint-processor-styled-components#208]
There is a lot of wrong lint results when I use stylelint like below:

![image](https://user-images.githubusercontent.com/5652404/44067612-f3561d3e-9fa8-11e8-9e65-12f4cb99b1f4.png)
![image](https://user-images.githubusercontent.com/5652404/44067614-f6085e16-9fa8-11e8-970c-1c4f71b52582.png)
![image](https://user-images.githubusercontent.com/5652404/44067831-ebcbc752-9fa9-11e8-8195-0788b0c3f38e.png)

**Comment by chinesedfan** [comment]
@ZxBing0066 Please refer to #193. Using [interpolation-tagging](https://www.styled-components.com/docs/tooling#interpolation-tagging) is one of workarounds.

If you want to solve it completely, feel free to join #110 and share your solution.
