### ISSUE TITLE
Upcoming API changes in styled-components v4

### ISSUE THREAD

**Issue by probablyup** [styled-components/stylelint-processor-styled-components#209]
Just a heads-up that we will be making some top-level API changes in v4 that may affect your library.

1) `injectGlobal` is being removed
2) `createGlobalStyle` is being added

`createGlobalStyle` can likely inherit any syntax highlighting rules you may have been using for `injectGlobal`, `styled.*` etc.

More info: https://github.com/styled-components/styled-components/pull/1867

**Comment by chinesedfan** [comment]
Seems solved by https://github.com/styled-components/stylelint-processor-styled-components/commit/63f270498bb7c2f42a8f4668826e62dd66d3bdf2.
