### ISSUE TITLE
No Interpolation Tag For Media Query

### ISSUE THREAD

**Issue by Undistraction** [styled-components/stylelint-processor-styled-components#217]
# Problem

The following code gives three errors:

- [stylelint] Unexpected duplicate selector ".selector283 ", first used at line 1 (no-duplicate-selectors)
- [stylelint] Unexpected duplicate selector ".selector283 ", first used at line 1 (no-duplicate-selectors)
- [stylelint] Unexpected duplicate selector ".selector283  > *", first used at line 4 (no-duplicate-selectors)

![screenshot 2018-09-12 18 13 53](https://user-images.githubusercontent.com/161489/45441705-b236b400-b6b7-11e8-8cbc-e2f25c76ee96.jpeg)

```javascript
const Layout = styled.div`
  ${getQuery(SMALL_UP)} {
    > * {
      flex: 0 1 50%;
    }
  }

  ${getQuery(MEDIUM_UP)} {
    > * {
      flex: 0 1 25%;
    }
  }
`
```

It would appear that the solution would be to use [interpolation tagging](https://www.styled-components.com/docs/tooling#interpolation-tagging), however there is no tag available for a media query. The closest would be `selector`, however that only removes the error from the first block: 

```javascript
const Layout = styled.div`
  ${/* sc-selector */ getQuery(SMALL_UP)} {
    > * {
      flex: 0 1 50%;
    }
  }

  ${/* sc-selector */ getQuery(MEDIUM_UP)} {
    > * {
      flex: 0 1 25%;
    }
  }
`
```
![screenshot 2018-09-12 18 27 14](https://user-images.githubusercontent.com/161489/45442278-7f8dbb00-b6b9-11e8-8dc1-e860bd31dcfd.jpeg)

**Comment by chinesedfan** [comment]
Duplicated of #202.
