### ISSUE TITLE
Unknown word CssSyntaxError on multiple interpolations per line

### ISSUE THREAD

**Issue by StevenLangbroek** [styled-components/stylelint-processor-styled-components#223]
I'm experiencing some trouble getting stylelint to behave, and I'm unsure whether this is a bug or I can maybe help the processor along a bit better. I have quite a simple component:

```js
import prop from 'lodash/fp/prop';

const sm = prop('theme.radii.sm');

Card.Image = styled(Img)`
  border-radius: ${sm} ${sm} 0 0;
`;
```

The 2 interpolations in 1 value (which are essential for controlling individual border radii) trips up the processor, leading to this error:

```bash
src/components-styleguidist/Experiments/Card.js
 42:41  ✖  Unknown word   CssSyntaxError
```

Any idea what's going on here? If it's a bug I'd gladly help fix it. Thanks ✌️

**Comment by chinesedfan** [comment]
@StevenLangbroek Sorry, can you provide more information, like stylelint config and related packages versions? I didn't reproduce this problem.

**Comment by StevenLangbroek** [comment]
Huh. Funny story. We discussed stylelint in a discussion about code quality, I suggested adding it to our project, only to find after running `yarn add` that it was already in the project. I was pretty sure it'd been upgraded to `latest`, but apparently we were still running - *wait for it* - `0.10.0` 😂
