### ISSUE TITLE
Support special comments

### ISSUE THREAD

**Issue by Ky6uk** [styled-components/stylelint-processor-styled-components#233]
It looks the current version of this processor doesn't support stylelint's special comments like
* `/* stylelint-disable */`
* `/* stylelint-disable-next-line */`
* etc. 

I was trying to suppress errors in my `.ts`/`.js` files by using those, but errors still exist.

**Comment by chinesedfan** [comment]
@Ky6uk Please follow the issue template. At least give enough information. Or we may not able to reproduce the problem. Thanks!

**Comment by Ky6uk** [comment]
It looks like a stylelint's bug.
