### ISSUE TITLE
Support for `stylefmt` to automatically fix lint errors

### ISSUE THREAD

**Issue by chaucerbao** [styled-components/stylelint-processor-styled-components#24]
I know this is still in early alpha stages, but I wanted to see what you thought about eventually adding support for [stylefmt](https://github.com/morishitter/stylefmt) to automatically fix stylelint errors.

**Comment by ismay** [comment]
I think that's outside of the scope of a stylelint processor. From the docs:

> Processors can enable stylelint to lint the CSS within non-stylesheet files. For example, let's say you want to lint the CSS within <style> tags in HTML. If you just feed stylelint your HTML code, you'll run into problems, because PostCSS does not parse HTML. Instead, you can create a processor that does the following

So basically this plugin makes your styled-components' css lintable with stylelint, and it makes sure that the line / column numbers are transformed back to the correct location for any errors. It isn't replacing any styles.

You might be able to use this plugin as an intermediary somehow though, but I'd say that that application would then have to be a separate library. On a related note, the stylelint team is working on a formatter like prettier for css: https://github.com/stylelint/stylelint/issues/2532.

Maybe you can notify them of your usecase and see what the options are.

**Comment by ismay** [comment]
I'll close this since I'd say it's out of scope for this package. Please let me know if you (or anyone else) feel otherwise or have any questions!
