### ISSUE TITLE
Using "component selector" and "pseudo selectors" together throws "selector-type-no-unknown"

### ISSUE THREAD

**Issue by rockingskier** [styled-components/stylelint-processor-styled-components#248]
When combining a "component selector" with a pseudo selector I receive the error `Unexpected unknown type selector "-styled-mixin1" (selector-type-no-unknown)stylelint(selector-type-no-unknown)`.

```jsx
import styled from "styled-components";

export const Input = styled.input`
  background-color: lightskyblue;
`;

export const Label = styled.label`
  ${Input} + & {
    color: skyblue;
  }


  ${Input}:focus + & {
//↑ "Unexpected unknown type selector "-styled-mixin1" (selector-type-no-unknown)stylelint(selector-type-no-unknown)"
    color: lightskyblue;
  }
`;

```

```json
{
  "name": "styled-lint",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "lint": "stylelint index.jsx"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "styled-components": "^4.1.3",
    "stylelint": "^9.10.1",
    "stylelint-config-recommended": "^2.1.0",
    "stylelint-config-styled-components": "^0.1.1",
    "stylelint-processor-styled-components": "^1.5.2"
  }
}
```

```json
{
  "processors": ["stylelint-processor-styled-components"],
  "extends": [
    "stylelint-config-recommended",
    "stylelint-config-styled-components"
  ]
}
```

## System:
 - OS: macOS 10.14.3
 - CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
 - Memory: 355.97 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 8.15.0 - ~/.nvm/versions/node/v8.15.0/bin/node
 - Yarn: 1.13.0 - /usr/local/bin/yarn
 - npm: 6.8.0 - ~/.nvm/versions/node/v8.15.0/bin/npm
## npmPackages:
 - styled-components: ^4.1.3 => 4.1.3
 - stylelint: ^9.10.1 => 9.10.1
 - stylelint-config-recommended: ^2.1.0 => 2.1.0
 - stylelint-config-styled-components: ^0.1.1 => 0.1.1
 - stylelint-processor-styled-components: ^1.5.2 => 1.5.2

https://gist.github.com/rockingskier/f5aa5d5468cf2e2ee55299adc4283e57.js

**Comment by chinesedfan** [comment]
The processor can not always parse interpolations with right things. But you can use [interpolation-tagging](https://www.styled-components.com/docs/tooling#interpolation-tagging) to help it. If you have ideas to make it more intelligent, feel free to send a PR or share your solution by an new issue.

```
import styled from "styled-components";

export const Input = styled.input`
  background-color: lightskyblue;
`;

export const Label = styled.label`
  ${/* sc-selector */ Input} + & {
    color: skyblue;
  }

  ${/* sc-selector */ Input}:focus + & {
    color: lightskyblue;
  }
`;
```
