### ISSUE TITLE
Unable to specify a specific import from a specific module

### ISSUE THREAD

**Issue by 43081j** [styled-components/stylelint-processor-styled-components#253]
So you provide two options:

* `moduleName`
* `importName`

Used like so:

```ts
// moduleName = module
import {x, y} from 'module';
x`test`; // parsed
y`test`; // parsed
```

```ts
// moduleName = module
// importName = y
import {x, y} from 'module';
x`test`; // parsed
y`test`; // parsed
y(whatever)`test`; // parsed
y.whatever`test`; // parsed
```

Surely this isn't how `importName` should work. I would expect only tagged templates which use the specified import name to be parsed, rather than ALL imported names _and_ the extra styled-specific stuff.

Like this:

```ts
// moduleName = module
// importName = y
import {x, y} from 'module';
x`test`; // NOT parsed
y`test`; // parsed
```

With this ability we could use the same component on other tagged template css libraries. Something like [LitElement](https://github.com/Polymer/lit-element/). But we can't yet because we over-parse:

```ts
css`this is css`; // parsed
html`this is html`; // parsed <- WRONG, it shouldn't be
```

**Comment by chinesedfan** [comment]
Agree with your feature request. But `importName` is there. We have use another option name or try to enhance it. Like single string means the old usage, and an array is used to provide names whitelist.
