### ISSUE TITLE
Support babel 7.8 syntax like null coalescing without plugins

### ISSUE THREAD

**Issue by mattdarveniza** [styled-components/stylelint-processor-styled-components#294]
Babel 7.8 supports es2020 syntax like optional chaining and null coalescing without the need for plugins, however this package still requires those plugins to be installed locally to ensure style lint doesn't throw its own babel parse errors.

As this package relies on babel 7.7, I suspect it would be a fairly straightforward upgrade. If maintainers are open to upgrading I'd be happy to do the legwork and put up a PR.

**Comment by chinesedfan** [comment]
> however this package still requires those plugins to be installed

As far as I know, Babel 8 has not been released yet. And do you mean "installed" or "set/config"?

If your requirement is not setting `parserPlugins` manually for optional chaining and null coalescing, please try 1.10.0.

**Comment by mattdarveniza** [comment]
Sorry I got a bit mixed up and meant `7.7 -> 7.8`. I've updated the title but it looks like you've addressed the issue in 1.10 anyway. Will close. Thanks.
