### ISSUE TITLE
Update tooling

### ISSUE THREAD

**Issue by ismay** [styled-components/stylelint-processor-styled-components#40]
- [ ] Add greenkeeper and greenkeeper-lockfile
- [x] Add prettier (#43, #44)
- [x] Add lintstaged (#43, #44)

**Comment by ismay** [comment]
@mxstbr I've sent a request to add greenkeeper to this repo. I've used it on almost all of my projects and have had nothing but good experiences with. It'll run our ci tests for new versions of dependencies within our specified range, to test whether they're breaking anything. If so, it'll notify us.

And for updates outside of the range in package.json it'll open a pr. In my opinion a great way to outsource/automate part the work of keeping an eye on dependencies.

**Comment by mxstbr** [comment]
Sure!

**Comment by ismay** [comment]
Cool, thanks!

**Comment by ismay** [comment]
@mxstbr Seems I can't enable greenkeeper on this repo without admin rights. Would you mind enabling it under this repo's `settings` > `integrations & services` > `greenkeeper`? I can take care of the rest.

**Comment by mxstbr** [comment]
Wait I thought I enabled it?

**Comment by mxstbr** [comment]
There we go: https://github.com/styled-components/stylelint-processor-styled-components/pull/61
