### ISSUE TITLE
Add external stylelint config

### ISSUE THREAD

**Issue by ismay** [styled-components/stylelint-processor-styled-components#45]
Which can be extended by users of this processor. It'll mean that we won't have to modify the stylelint result anymore, and that people can still override any of the rules we define (should they want to do so).

It'll need to be a separate library, but still needs to be linked to a particular release of this lib, so specifying the config as a peerDependency would probably be best.

Ref #9

**Comment by mxstbr** [comment]
Should we maybe go for a `lerna` monorepo?

**Comment by ismay** [comment]
Yeah that would be great. But unfortunately it wouldn't work with greenkeeper (https://github.com/greenkeeperio/greenkeeper/issues/139), for now at least. 

I think to me greenkeeper outweighs the ease of having both projects in a monorepo. It would be a bit awkward, but I think the config would also require considerably less maintenance, so there wouldn't be a lot of switching.

But please feel free to let me know if you feel otherwise, I might be biased :).

**Comment by ismay** [comment]
https://github.com/styled-components/stylelint-config-styled-components-processor

**Comment by emilgoldsmith** [comment]
I guess we can close this issue now? Or should we wait until we merge in 1.0?

**Comment by ismay** [comment]
As long it's on the 1.0 milestone we could just review the linked issues after merging. But closing also seems fine.

**Comment by emilgoldsmith** [comment]
Yeah I guess we can just do a mass-close when we merge in v1.0

**Comment by mxstbr** [comment]
Let's close it so the milestone shows the progress!
