### ISSUE TITLE
Add autofix support

### ISSUE THREAD

**Issue by trevordmiller** [styled-components/stylelint-processor-styled-components#50]
Currently running `stylelint --fix` doesn't effect styles defined in JS using styled-components. It would be awesome if this feature could be added :)

Thank you!

**Comment by ismay** [comment]
Yeah that definitely would be awesome. But currently stylelint can't `--fix` styles in combination with a processor. See here: https://github.com/stylelint/stylelint/issues/2592

If in the future stylelint allows for this combination we could take a look at it.

**Comment by ekfuhrmann** [comment]
Stylelint now allows autofixing errors ([link](https://stylelint.io/user-guide/cli/#autofixing-errors)). Any chance we can revisit adding this to styled components now?

**Comment by emilgoldsmith** [comment]
Your link isn't about `--fix` being supported for processors is it? That's just the normal support for `--fix`. So it's not relevant to our issue. Feel free to try and add the support though and submit a PR to Stylelint!

**Comment by WebTravel** [comment]
https://github.com/stylelint/stylelint/pull/3261
