### ISSUE TITLE
Doesn't handle one-line css interpolations

### ISSUE THREAD

**Issue by emilgoldsmith** [styled-components/stylelint-processor-styled-components#62]
As I was checking the new merged code from #52 an edge case just popped into my mind. I already wrote breakings tests for it, just also wanted an issue to reference so I'll reference this issue as I push the new PR.

**Comment by ismay** [comment]
Ah yeah, good catch. We're missing a couple of test cases looking at our coverage stats, seems like that's one of the cases we're still missing.
