### ISSUE TITLE
Support ignoring rules outside of TTL

### ISSUE THREAD

**Issue by emilgoldsmith** [styled-components/stylelint-processor-styled-components#64]
I know we closed #56, but I thought about it a bit and I think I could add support for it pretty simply. 

You just use the already implemented babylon parser and then every time you hit a comment outside a TTL you check if it fits `/stylelint-(?:enable|disable)/` if it does you add it to an array, and every time you encounter a TTL you inject all the comments you pushed to the array to the top of the TTL to be parsed, in that way it will also support someone later using `stylelint-enable`. This should handle all cases from the [docs](https://stylelint.io/user-guide/configuration/#turning-rules-off-from-within-your-css) as we of course could just ignore `stylelint-disable-(?:next-)?line` as those should only be used within.

I think it would be quite a nice intuitive addition. I of course think so because I thought it would intuitively work like eslint, and I could see why others would think the same.

I'll probably submit a PR in the near future adding this in.

**Comment by ismay** [comment]
@emilgoldsmith Hey, just wanted to let you know that I'm currently traveling, but I'll take a look at the pr's and issues asap.

**Comment by emilgoldsmith** [comment]
@ismay no problem! Enjoy your travels, take your time :).

And thanks for the heads up, appreciate it :).
