### ISSUE TITLE
Unknown word - CssSyntaxError

### ISSUE THREAD

**Issue by JonWallsten** [styled-components/stylelint-processor-styled-components#73]
Hi!
Not sure if this is bug since I wasn't the one who set up our tooling.
But after upgrading to 0.2.0 yesterday I'm no longer able to use the css helper in nested rules.
Since I don't know how to properly set up a fresh environment I can't really prove it's a problem with the stylelint processor. But this was the only package I updated yesterday besides postcss.
 
```
const css = css`
  color: #FFF;
`

const div = styled(div)`
  span {
    ${css}
  } 
`
``` 

Feel free to close if you don't think it's a bug.

**Comment by emilgoldsmith** [comment]
Hmm that surprises me, I'll check it out quickly

**Comment by emilgoldsmith** [comment]
Yep that was a bug in my code, sorry about that, and thanks for reporting!

**Comment by emilgoldsmith** [comment]
I had missed a case in a previous PR, we'll get #74 merged in quickly after review and publish a 2.1 so you can hopefully soon have this fixed :).

**Comment by JonWallsten** [comment]
No worries mate! Thanks for fixing it!

**Comment by emilgoldsmith** [comment]
@JonWallsten 0.2.1 published :). Hope that fixes your problems, and feel free to report any other bugs not already in the issues list if you find any :).
