### ISSUE TITLE
Stylelint v3+ requires plugins to expose a ruleName

### ISSUE THREAD

**Issue by willdavidow** [styled-components/stylelint-processor-styled-components#78]
Just set up stylelint for my project, very basic setup with one file using styles currently.

Upon running stylelint against my project, I received the following error:

```zsh
Error: stylelint v3+ requires plugins to expose a ruleName. 
The plugin "/Users/will/Development/main-site/node_modules/stylelint-processor-styled-components/lib/index.js" is not doing this, so will not work with stylelint v3+. 
Please file an issue with the plugin.
```

Not sure if this is an issue with my config, or that I'm using a too-new version of stylelint?

**Comment by emilgoldsmith** [comment]
You're apparently adding our package as a plugin, which means extra rules, not a processor which is what this is. Refer to the README for proper setup :).

**Comment by willdavidow** [comment]
My mistake - I put it in the wrong field -thanks for responding!
