### ISSUE TITLE
One line style considered as error

### ISSUE THREAD

**Issue by BjornMelgaard** [styled-components/stylelint-processor-styled-components#89]
This snipped
```
export const A = styled.a`color: ${({ theme }) => theme.colors.main};` 
```

throws error

```
app/components/Theme.js
  8:13  ✖  Expected single space after "{" of a single-line block                                      block-opening-brace-space-after
           (block-opening-backtick-space-after)
  8:31  ✖  Expected single space before "}" of a single-line block                                     block-closing-brace-space-before
           (block-closing-backtick-space-before)
```

The fact is that Im using prettier and prettier formats to this form automatically

**Comment by BjornMelgaard** [comment]
workaround

```
{
  "processors": ["stylelint-processor-styled-components"],
  "extends": "stylelint-config-standard",
  "syntax": "scss",
  "rules": {
    "block-opening-brace-space-after": "never-single-line",
    "block-closing-brace-space-before": "never-single-line"
  }
}

```

**Comment by emilgoldsmith** [comment]
I don't believe this is our problem either. More so a problem of a combination of your linting rules plus prettier. See [this issue](https://github.com/prettier/prettier/issues/2291) in the prettier repo and there are many others, as they treat tagged template literals in a way that causes problems for styled components.

What you call a workaround is simply a change of config for your preferences, linting always is, you have to choose your preferences, this isn't related to our implementation.
