### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by emilgoldsmith** [styled-components/stylelint-processor-styled-components#91]
We should probably have a changelog, yeah? Especially now that we're introducing some breaking changes here and there. Any preferences for how to manage it?

**Comment by mxstbr** [comment]
SGTM!

**Comment by emilgoldsmith** [comment]
Any specific formats you usually follow? Or maybe some tech you use to synch Github releases to a CHANGELOG ? Or something similar? Should we keep both of them or one of them? Any thoughts?

**Comment by ismay** [comment]
I usually just do it manually. You could use something that generates a changelog by parsing commit messages, which means we'd have to format our commit messages in a way that the generator understands.

@emilgoldsmith I understand that you're already using np, we could hook into that with an npm script, and use something like this: https://www.npmjs.com/package/generate-changelog.

**Comment by emilgoldsmith** [comment]
Yeah that sounds interesting @ismay. I can see several tools online that do cool things with changelogs. One I can't seem to find that I think would be really cool would be if you could just write a CHANGELOG file and then have it automatically sync to Github Releases using [this api](https://developer.github.com/v3/repos/releases/#create-a-release). I can't believe nothing like that already exists... Maybe I'm just bad at searching.

Maybe for now we just start with manually updating both of them, as also if we used the package you linked to above @ismay (which sounds pretty cool) we'd have to start adhering to that commit message format, yeah?

**Comment by emilgoldsmith** [comment]
[Here](https://github.com/olivierlacan/keep-a-changelog/issues/1) was the issue I remembered reading. Here someone created [chandler] which does exactly what I was talking about, the only drawback is it uses Ruby instead of node / npm, so yeah maybe not something worth using because of that, but interesting nonetheless.

**Comment by ismay** [comment]
> Maybe for now we just start with manually updating both of them, as also if we used the package you linked to above @ismay (which sounds pretty cool) we'd have to start adhering to that commit message format, yeah?

Yeah, it'd only work if we'd follow their commit format. Yeah I think doing it manually is fine up until a certain project size.

**Comment by mxstbr** [comment]
I think we'll be fine doing it manually for now, in the future we can half-automate it like the styled-components repo by having a bot that forces people to add a CHANGELOG entry when they submit a PR!

**Comment by emilgoldsmith** [comment]
Yep sounds good :).

**Comment by ismay** [comment]
Btw., I haven't checked what actually went into 0.4.0, but does that still need to go into the changelog? After that I'll add my renaming of the stylelint config as well.

**Comment by emilgoldsmith** [comment]
Oh I hadn't even seen we had a CHANGELOG yet haha, Did we have this when I created this issue? If so sorry haha, I can't believe I didn't check.

But yeah the last few publishes should of course be in the CHANGELOG as well, I can handle that in the near future. It should be quite clear from merge commits as at least when I've published there should be a commit named the version (and of course the tags)

**Comment by ismay** [comment]
@emilgoldsmith By the way, for generating the changelog we could use these libraries to automate it:

- https://github.com/conventional-changelog/conventional-changelog
- https://github.com/marionebl/commitlint

Commitlint would enfore commit style to be something that conventional-changelog can parse (and subsequently generate a changelog from).
