### ISSUE TITLE
Update package.json github references

### ISSUE THREAD

**Issue by mike3run** [styled-components/stylelint-processor-styled-components#92]
Specially the bugs and homepage since they point to a 404 right now

https://github.com/styled-components/stylelint-processor-styled-components/blob/master/package.json#L29-L31

**Comment by emilgoldsmith** [comment]
Oh yeah haha. We just fixed up #85 but didn't see it was also those 2 places. Cheers!

**Comment by ismay** [comment]
Duplicate of #48

**Comment by emilgoldsmith** [comment]
> Duplicate of #48
Oh yeah you're right, you already had this pointed out. In that case I'll close #48 :).

**Comment by ismay** [comment]
Yeah the issue was a bit vaguely worded. I should've just taken care of it immediately, thanks for handling it!
